CREATE DATABASE SISTEMACONTROLACCESO
GO
USE SISTEMACONTROLACCESO
GO

CREATE TABLE CARGO(
    IDCARGO INT IDENTITY PRIMARY KEY,
    NOMCARGO VARCHAR(100))
GO

CREATE TABLE PERSONA(
IDPER INT IDENTITY,
DNI VARCHAR(10) PRIMARY KEY,
NOMBRE varchar(100),
APELLIDOS varchar(100),
TELF VARCHAR(20),
IDCARGO INT FOREIGN KEY REFERENCES CARGO(IDCARGO),
SECCION INT default 1,
SUBSECCION INT default 1,
ESTADO BIT DEFAULT 1)
GO

CREATE TABLE CONTROLASISTENCIA(
IDCONTROL INT IDENTITY PRIMARY KEY,
DNI VARCHAR(10) FOREIGN KEY REFERENCES PERSONA(DNI),
DNIBARRA VARCHAR(100),
H_ING1 DATETIME,
H_ING2 DATETIME,
H_SAL1 DATETIME,
H_SAL2 DATETIME,
FECHAING DATE DEFAULT GETDATE())
GO

INSERT INTO CARGO VALUES('ADMINISTRADOR');
INSERT INTO CARGO VALUES('OPERADOR');
INSERT INTO CARGO VALUES('SECRETARIA');

--nuevo cargo en dbo.CARGO. Verifica si el cargo ya existe
CREATE PROC sp_registrarCargo
@NOMCAR VARCHAR(100)
AS
IF (SELECT COUNT(*) FROM CARGO WHERE NOMCARGO=@NOMCAR)>0
BEGIN
    PRINT 'ESTE CARGO YA ESTA REGISTRADO'
END
ELSE
BEGIN
    INSERT INTO CARGO(NOMCARGO) VALUES(@NOMCAR)
END

--nueva persona en dbo.PERSONA. Verifica si la persona ya está registrada utilizando su nombre
create PROC sp_registrarPersonal
@DNI varchar(10),
@NOM varchar(100),
@APE varchar(100),
@TELE varchar(20),
@IDCARGO INT
AS
IF (SELECT COUNT(*) FROM PERSONA WHERE NOMBRE=@NOM)>0
BEGIN
PRINT 'EL PERSONAL YA SE ENCUENTRA REGISTRADO'
END
ELSE
BEGIN
INSERT INTO PERSONA (DNI,NOMBRE,APELLIDOS,TELF,IDCARGO)values(@DNI,@NOM,@APE,@TELE,@IDCARGO)
END

--muestra todos los cargos registrados
CREATE PROC PA_LISTARCARGO
AS
BEGIN
SELECT * FROM CARGO
END

--Elimina un cargo de dbo.CARGO utilizando el ID del cargo como variable
CREATE PROC eliminarCargo
@COD INT
AS
BEGIN
DELETE FROM CARGO WHERE IDCARGO=@COD
END

--muestra personal de empleados y cargo. unión entre dbo.PERSONA y dbo.CARGO para obtener el nombre del cargo asociado a cada persona.
CREATE PROC pa_listarPersonal
AS
SELECT IDPER,DNI,NOMBRE,APELLIDOS,TELF,c.NOMCARGO,ESTADO FROM dbo.PERSONA p INNER JOIN CARGO c ON p.IDCARGO=C.IDCARGO

--actualiza info del personal - dni no debe cambiar
CREATE PROC sp_actualizarPersonal
@DNI VARCHAR(10),
@NOM VARCHAR(100),
@APE VARCHAR(100),
@TELE VARCHAR(20),
@IDCARGO INT
AS
BEGIN
IF (SELECT COUNT(*) FROM PERSONA WHERE DNI = @DNI) = 0
BEGIN
PRINT 'LA PERSONA NO EXISTE'
    END
ELSE
BEGIN
UPDATE PERSONA
SET NOMBRE = @NOM,
APELLIDOS = @APE,
TELF = @TELE,
IDCARGO = @IDCARGO
WHERE DNI = @DNI
PRINT 'DATOS DE LA PERSONA ACTUALIZADOS CORRECTAMENTE'
END
END

--
create proc sp_registroAsistenciaPersonal
@DNI VARCHAR(10)
AS
DECLARE @DIA INT,@MES INT,@ANHO INT,@CANT INT,@COD INT
SET  @DIA=(SELECT DATEPART(DD,GETDATE()))
SET  @MES=(SELECT DATEPART(MM,GETDATE()))
SET  @ANHO=(SELECT DATEPART(YY,GETDATE()))
SET @CANT=(SELECT COUNT(*) FROM CONTROLASISTENCIA WHERE DNI=@DNI and DATEPART(DD,H_ING1)=@DIA 
AND DATEPART(MM,H_ING1)=@MES AND DATEPART(YY,H_ING1)=@ANHO)

SET @COD=(SELECT IDCONTROL FROM CONTROLASISTENCIA WHERE DNI=@DNI and DATEPART(DD,H_ING1)=@DIA 
AND DATEPART(MM,H_ING1)=@MES AND DATEPART(YY,H_ING1)=@ANHO)

IF @CANT=0
	BEGIN
		INSERT INTO CONTROLASISTENCIA (DNI,H_ING1) VALUES(@DNI,GETDATE())
	END
	ELSE
	BEGIN
	SET @CANT =(SELECT COUNT(*) FROM CONTROLASISTENCIA WHERE IDCONTROL=@COD AND H_SAL1 IS NULL)
		IF @CANT=1
		BEGIN
			UPDATE CONTROLASISTENCIA SET H_SAL1=GETDATE() WHERE IDCONTROL=@COD
		END
		ELSE
		BEGIN
			SET @CANT =(SELECT COUNT(*) FROM CONTROLASISTENCIA WHERE IDCONTROL=@COD AND H_ING2 IS NULL)
			IF @CANT=1
			BEGIN
				UPDATE CONTROLASISTENCIA SET H_ING2=GETDATE() WHERE IDCONTROL=@COD
			END
			ELSE
			BEGIN
				UPDATE CONTROLASISTENCIA SET H_SAL2=GETDATE() WHERE IDCONTROL=@COD
		END
	END
END

ALTER PROC pa_filtrarDatosPersonal
@dni varchar(10)
AS
BEGIN
    -- Verificar si el DNI existe
    IF (SELECT COUNT(*) FROM PERSONA WHERE DNI = @dni) = 0
    BEGIN
        PRINT 'El personal con el DNI proporcionado no está registrado.'
    END
    ELSE
    BEGIN
        -- Retorna más información sobre la persona, incluyendo cargo y estado
        SELECT p.NOMBRE, p.APELLIDOS, p.TELF, c.NOMCARGO
        FROM PERSONA p
        INNER JOIN CARGO c ON p.IDCARGO = c.IDCARGO
        WHERE p.DNI = @dni
    END
END

exec pa_filtrarDatosPersonal '12344321'

select * from dbo.CONTROLASISTENCIA
select * from PERSONA
select * from CARGO

select top 10 * from CONTROLASISTENCIA